### ISSUE TITLE
PyPi Package

### ISSUE THREAD

**Issue by javadr** [Aghababaei/PhD-Seeker#10]
Dear Amin, 

I've made it available via the `PyPi` repository, another step towards usage simplicity. ;D
Create an account there if you like, and let me know your id to add you to the repository. 

Best, Javad

**Comment by javadr** [comment]
Could you test it on `Windows`? I have no access to `Windows` OS.

**Comment by Aghababaei** [comment]
Dear Javad,

It is greatly appreciated that you are continuously working to remove obstacles.
Well done! It works on Windows OS properly.
As to the `PyPi` repository, `Aghababaei` is my ID should you wish to add me.

Regards,
Amin

**Comment by javadr** [comment]
Thanks for testing on windows. 
As far as I remember, some applications need to be added to the Windows PATH manually. 
If this is true in our case, could you update the `Readme.md` file for illiterate people on how to fix the issue?

**Comment by javadr** [comment]
Did you check it?

**Comment by Aghababaei** [comment]
Your point is well taken.
Those who did not check the PATH option when installing Python may encounter this problem.
I am going to write a brief instruction for Windows users today.

**Comment by javadr** [comment]
Thanks. 
Please close this issue at the end of your work.

**Comment by Aghababaei** [comment]
Done!

**Comment by javadr** [comment]
Thank you very much. 

A weird issue happened with your last commit. 
We lost version 0.3.14 while it is available via PyPi and in my other fork from this repo. 
Did you use `git pull` before starting to your modification? 
BTW, I made it again with another commit.

**Comment by Aghababaei** [comment]
I noticed that there is something wrong with the repository, and, as you mentioned, it was totally weird! Hopefully, you recognized the problem.
Strangely, I had noticed the 'pull' command before 'push'ing!
The problem might have been caused by some connection problems on my end while `pull`ing.

Thanks a lot.
