### ISSUE TITLE
Removing unnecessary files

### ISSUE THREAD

**Issue by javadr** [Aghababaei/PhD-Seeker#11]
What do you think about removing the following files from the repo as they seem unnecessary?

```
PhD_Positions_2022-08-01.csv
PhD_Positions_2022-08-01.xlsx
```

**Comment by Aghababaei** [comment]
You are right Javad. It seems completely unnecessary. Watching potential results, however, could be motivating and helpful for newcomers and those who are not familiar with working with codes.

What about moving them to a `sample_results` folder? (although it seems unnecessary as well!)

**Comment by javadr** [comment]
Yep, it might be useful for someone to see the output in advance. 
Could you take a look at the following link and validate your theory about that?
https://github.com/Aghababaei/PhD-Seeker/graphs/traffic

BTW, do what you think is good. I strongly suggest removing them from the root of the repository even by deleting them all or by moving under the other directory as you mentioned above.

**Comment by Aghababaei** [comment]
Just convinced! We can get rid of them!

The repository has seen 1269 viewers, among 2 percent of which care about the samples, meaning that hopefully, most `phdseeker` users are already familiar with how to work with codes (thanks to the comprehensive README).

**Comment by javadr** [comment]
Done!
